# Generated by Django 3.2.9 on 2021-12-01 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('square_feet', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lot_size', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('listing_date', models.DateTimeField()),
                ('description', models.TextField(max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('main_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('image_1', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('image_2', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('image_3', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('image_4', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('image_5', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
