# Generated by Django 3.2.9 on 2021-12-01 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('hired_date', models.DateTimeField(default=datetime.datetime(2021, 11, 30, 17, 23, 58, 862403))),
                ('image', models.ImageField(null=True, upload_to='photo/%Y/%m/%d')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
