# Generated by Django 3.2.9 on 2021-12-02 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hired_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 16, 40, 52, 688892)),
        ),
    ]
