# Generated by Django 3.2.9 on 2021-12-05 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_alter_realtor_hired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='title',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtor',
            name='hired_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 14, 30, 46, 927564)),
        ),
    ]
