# Generated by Django 3.2.9 on 2021-12-05 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0006_auto_20211205_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
