# Generated by Django 3.2.9 on 2021-12-05 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0008_realtor_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='image',
            new_name='realtor_image',
        ),
    ]
