# Generated by Django 3.2.9 on 2021-12-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0009_rename_image_realtor_realtor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='seller_of_month',
            field=models.BooleanField(default=False),
        ),
    ]
